#!/bin/bash

# The script obtains the interfaces of the specified virtual systems.
# The output format is CSV: VS name, interface name, IP address, mask length, MTU.

# Dependencies:
# - lib_sh/gateways.bash

bash_lib_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )/lib_sh"

# shellcheck source=/dev/null
# shellcheck source=../lib_sh/gateways.bash      # FIXME: This directive does not work.
source "${bash_lib_dir}/gateways.bash"


if [ -z "$user" ] ; then
    user="$LOGNAME"
fi

if [ -z "$password" ] ; then
    read -rs -p "Enter password for $user: " password
fi

if [ -z "$gateways" ] ; then
    gateways="$(get_gateways CpmiVsClusterNetobj)"
fi


for vs in $gateways ; do
    vsx_provisioning_tool -s 127.0.0.1 -u "$user" -p "$password" -o "show vd name $vs" \
        2> >(grep -v '^Version ' >&2)   # Filter Version lines from stderr.
done |
    sed -En 's%^add interface vd ([^ ]+) name ([^ ]+) ip ([^ /]+)/([^ ]+)( mtu ([^ ]+))?.*$%\1,\2,\3,\4,\6%p'
