#!/bin/bash

# sgm_monitor_links

# Monitor the link status of the specified network interfaces.
# They are checked with pauses of the given duration. The results
# are logged to a file with timestamps.

links=(
    ethsBP1-01
    ethsBP3-01
)

sleep_duration=0.5

hostname=$(hostname -s)
file_time=$(date +%Y-%m-%dT%H-%M)

log_file="${file_time}_${hostname}_sgm_monitor_links.log"

# --- end of parameters

link_monitor () {
    # Show network interface status.
    # $1 - network interface name, e.g. ethsBP1-01
    ethtool "$1" |
        grep -Ev '   [0-9]+00base[A-Z0-9_]+/Full *$'    # Throw away lines with supported link modes.
}

time_stamp () {
    date -Ins
}

while true ; do
    for link in "${links[@]}" ; do
        echo "=== $(time_stamp) $link ==="
        link_monitor "$link"
        echo
    done >> "$log_file"
    echo >> "$log_file"
    sleep "$sleep_duration"
done
